#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
. "$HOME/.cargo/env"

if [ -e /home/ljalouzot/.nix-profile/etc/profile.d/nix.sh ]; then . /home/ljalouzot/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
