# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

function check_and_handle_venv() {
  if [[ -z "$VIRTUAL_ENV" ]]; then
    if [[ -d ./.venv ]]; then
      echo "📦 Activating virtual environment in $(pwd)/.venv"
      . .venv/bin/activate
    fi
  else
    parentdir="$(dirname "$VIRTUAL_ENV")"
    if [[ "$PWD"/ != "$parentdir"/* ]]; then
      echo "🔌 Deactivating virtual environment from $VIRTUAL_ENV"
      deactivate
    fi
  fi
}

function cd() {
  builtin cd "$@"
  check_and_handle_venv
}

co() {
  exec connect tunnel
}


export PATH="$HOME/bin:$PATH"

if [[ "$(hostname)" == *"jean-zay"* ]]; then
  . "$HOME/.local/bin/env"
  cd ~/work
fi

# Check for virtual environment at login
check_and_handle_venv

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Custom functions
alias t=tmux
alias ta="tmux attach"
alias sm="squeue --me"